title = "Hijauan Valdor - Phase 7"
# baseURL = "https://hijauanvaldor.com.my/phase-7"
baseURL = "https://ytyeoh.github.io/hv7"
languageCode = "en-us"
theme = "hugo-universal-theme"

# hugo server --buildDrafts --bind 192.168.0.115 --baseURL http://192.168.0.115
DefaultContentLanguage = "en"
# SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
enableRobotsTXT = true



# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
disqusShortname = "devcows"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "asdd"

# Define the number of posts per page
paginate = 10

[menu]

# Main menu

[[menu.main]]
    identifier="about"
    name = "about"
    url  = "#about"
    weight = 6

[[menu.main]]
    identifier="floor plan"
    name = "floor plan"
    url  = "#floor-plan"
    weight = 5

[[menu.main]]
    identifier = "location"
    name = "site plan"
    url  = "#site-plan"
    weight = 4

[[menu.main]]
    identifier = "contact"
    name = "Location"
    url  = "#location"
    weight = 3
[[menu.main]]
    identifier = "gallery"
    name = "gallery"
    url  = "#gallery"
    weight = 2
[[menu.main]]
    identifier = "specifications"
    name = "specifications"
    url  = "#specifications"
    weight = 1


[params]

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "default"

    # Enable the contact form by entering your Formspree.io endpoint url
    formspree_action = "./email.php"
    contact_form_ajax = false
    contact_title = "REGISTER YOUR INTEREST"
    contact_text_1 = "in the Hijauan Valdor Phase 7: Single Storey Semi-Detached Home"
    contact_us = "Have questions? reach us at:"
    email = "enquiries@asasdunia.com"

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "img/logo.png"
    logo_small = "img/logo-small.png"
    copyright1 = "Developer : Asas Dunia Berhad (198201014764 94528T) Land Owner : Mastiara Construction Sdn Bhd (107901008189 52475W) Developer License :2687/03-2024/0147(A) Validity: 5.3.22 - 4.3.24 Advertising & Sales Permit: 2687-62/03-2024/0184 Validity: 5.3.22 - 4.3.24 December 2024 Authority approving building plan : Majlis Bandaraya Seberang Perai. Building plan reference no. : MBSP/40/20-75/80. Expected date of completion : December 2023. Single Storey Semi-Detached : 158 units. Price : RM700,000-RM1,031,600Freehold, Free from encumbrances, 5% discount for Bumiputera. THIS ADVERTISEMENT HAS BEEN APPROVED BY THE MINISTRY OF HOUSING."
    copyright2 = "*All drawings and illustrations herein are artist’s impressions only. All plans, specifications, measurements and information contained herein are subject to variations, amendments and changes as may be required by the relevant authorities or project architect without prior notification to purchase and cannot form part of an offer or contract.<br><br>COPYRIGHT © {year} ASAS DUNIA BERHAD. ALL RIGHTS RESERVED."

    download = "https://abc.com/doanload"
    book_now = "contact"

[params.add1]
    name= "Penang Sales Office"
    text = "Wisma Asas,<br>  No.228, Lebuh Chulia,<br>10200 Penang."
    tel="04-255 9999"
    fax="04-255 9888"
[params.add2]
    name= "Hijauan Hills Sales Gallery"
    text = "No.2, Jalan Hijauan Hills 3,<br> Hijauan Hills,14120<br>  Simpang Ampat, Penang."
    tel="04-563 3999"
    fax="04-563 1999"
[params.floor_plan]
    land_area= "19’ x 71.85’"
    built_up = "19’ x 43.8’" 
    floor_plan_a = "Flr_Plan_Type_A"
    floor_plan_b = "Flr_Plan_Type_B"
[params.site_plan]
    img = "Site_plan"
    icon = "low-den"
    digit = "50"
    quantity = "Units"
    map1 = "map1"
    map2 = '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d7946.255295997723!2d100.48926053094233!3d5.242633538182633!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x304ab6e7868bb505%3A0x1b7aa7ac42067bf9!2s942-931%2C%20Jalan%2010%2C%20Perkampungan%20Valdor%2C%2014200%20Sungai%20Jawi%2C%20Pulau%20Pinang!5e0!3m2!1sen!2smy!4v1628072627763!5m2!1sen!2smy" width="100%" height="100%" style="border:0;" allowfullscreen="" loading="lazy"></iframe>'

# Enable or disable top bar with social icons

[params.carousel]
    enable = true
    h2a = "single storey"
    h2b = "semi-detached homes"
    p = "by Asas Dunia"
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = true
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.


[params.home]
    enable = true
    title = "phase 6"
    subtitle = "Freehold & Guarded <br>Sungai Bakap"
    name = "iris"
    size = "1,365 sqft"
    type= "SINGLE STOREY <br> TERRACE HOUSE"
    
[params.description]
    title = "Peace and Tranquility, <br>Enclaved in Greenery."
    description = "<p>Primely positioned at the centre of Southern Seberang Perai, Hijauan Valdor Phase 7 puts you near flourishing towns such as Simpang Ampat, Nibong Tebal, Sungai Bakap, Alma and Batu Kawan. It provides swift access to Penang Island for added convenience  <br><br> Fulfilling your needs and engaging in the lifestyle of your dreams are a breeze. Public amenities and social facilities, along with educational, recreational, commercial and industrial destinalions are close by.</p>"

[params.access]
    [[params.access.main]]
        name = "Schools"
        icon = "book"
        [[params.access.main.sub]]
            name = "SMJK(C) Jit Sin 2"
            distance = "6.0"
            time = "2"
        [[params.access.main.sub]]
            name = "SMK Valdor"
            distance = "1.6"
            time = "2"
        [[params.access.main.sub]]
            name = "SJK(C) Kampung Valdorr"
            distance = "1.8"
            time = "2"
    [[params.access.main]]
        name = "Access to Penang Island"
        icon = "bridge"
        [[params.access.main.sub]]
            name = "2nd Penang Bridge"
            distance = "6.0"
            time = "2"
        [[params.access.main.sub]]
            name = "Penang Bridge"
            distance = "18.0"
            time = "2"
    [[params.access.main]]
        name = "Markets"
        icon = "market"
        [[params.access.main.sub]]
            name = "Valdor Market"
            distance = "2.3"
            time = "2"
        [[params.access.main.sub]]
            name = "TESCO"
            distance = "9.0"
            time = "2"
        [[params.access.main.sub]]
            name = "JUSCO"
            distance = "9.0"
            time = "2"
    [[params.access.main]]
        name = "Neighbouring Township"
        icon = "township"
        [[params.access.main.sub]]
            name = "Batu Kawan"
            distance = "6.0"
            time = "2"
        [[params.access.main.sub]]
            name = "Bukit Mertajam"
            distance = "16.0"
            time = "2"
        [[params.access.main.sub]]
            name = "Alma"
            distance = "10.0"
            time = "2"
        [[params.access.main.sub]]
            name = "Simpang Ampat"
            distance = "4.7"
            time = "2"
        [[params.access.main.sub]]
            name = "Sungai Bakap"
            distance = "2.0"
            time = "2"
        [[params.access.main.sub]]
            name = "Nibong Tebal"
            distance = "9.0"
            time = "2"
[params.gallery]
  img = "17"

[params.specifications]
    [[params.specifications.img]]
    img = "text"
    [[params.specifications.img]]
    img = "text2"
    [[params.specifications.img]]
    img = "text3"
    [[params.specifications.img]]
    img = "text4"
    [[params.specifications.img]]
    img = "text5"
    [[params.specifications.img]]
    img = "text6"